name: lando-tooling
compose:
  - compose.yml
events:
  post-start:
    - node: whoami | grep node
services:
  node:
    type: node:14
tooling:
  php:
    service: php
    description: Run php commands
    cmd: php
  iamroot:
    service: php
    cmd: echo "$HOME" && echo "$(id)" > /whoami
    user: root
  whoami:
    service: php
    cmd: id
  nodeme:
    service: node
    cmd: whoami
  stillme:
    cmd:
      - node: whoami
  notme:
    service: node
    cmd: whoami
    user: www-data
  pipesandstuff:
    service: node
    cmd:
      - env | grep LANDO_ > pipe.txt
      - echo "more" >> pipe.txt
  test:
    service: php
    cmd:
      - php -v
      - php -m
    description: Run all the tests
  word:
    service: web
    cmd: /app/word.sh
    level: app
    options:
      word:
        passthrough: true
        alias:
          - w
        describe: Print what the word is
        interactive:
          type: input
          message: What is the word?
          default: bird
          weight: 600
  dynamic:
    cmd: env
    service: :service
    options:
      service:
        default: web
        alias:
          - s
        describe: Run a different service
  env:
    cmd:
      - php: env
      - web: env
    description: Print environment variables for a few things
  busted:
    service: web
    cmd: i-do-not-exist
  envvar:
    service: web
    cmd: echo "$TAYLOR"
    env:
      TAYLOR: swift
  listfiles:
    service: web
    cmd: ls -lsa /app/*
  cmdsub:
    service: web
    cmd: echo "`ls -lsa /app/*`"
  oneliner:
    service: web
    cmd: if [ ! -z "$SPECIAL" ]; then echo "$SPECIAL"; fi
    env:
      SPECIAL: HOLLA
  workdir:
    cmd: pwd
    service: web
    dir: /tmp
