name: "@lando/cli"
hooks:
  cli:
    done:
      - "./hooks/cache-rebuild.js"
    init:
      - "./hooks/init.js"
    init-preflight:
      - "./hooks/checks.js"
    prerun:
      - "./hooks/prerun.js"
    postrun:
      - "./hooks/postrun.js"
