name: Build Utility Images

on:
  # Uncomment below for testing purposes
  # pull_request:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-22.04
    env:
      TERM: xterm
    strategy:
      matrix:
        include:
          - image: util
            tag: 4
            context: plugins/lando-core/types/utility

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag suffix
        id: pr
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "::set-output name=TAG_SUFFIX::-edge"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
