name: Build PHP Images

on:
  # Uncomment below for testing purposes
  pull_request:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-20.04
    env:
      TERM: xterm
    strategy:
      matrix:
        include:
          - image: php
            tag: 8.1-fpm-4
            context: plugins/lando-services/services/php/8.1-fpm
          - image: php
            tag: 8.1-apache-4
            context: plugins/lando-services/services/php/8.1-apache
          - image: php
            tag: 8.0-fpm-4
            context: plugins/lando-services/services/php/8.0-fpm
          - image: php
            tag: 8.0-apache-4
            context: plugins/lando-services/services/php/8.0-apache
          - image: php
            tag: 7.4-fpm-4
            context: plugins/lando-services/services/php/7.4-fpm
          - image: php
            tag: 7.4-apache-4
            context: plugins/lando-services/services/php/7.4-apache
          - image: php
            tag: 7.3-fpm-4
            context: plugins/lando-services/services/php/7.3-fpm
          - image: php
            tag: 7.3-apache-4
            context: plugins/lando-services/services/php/7.3-apache
          - image: php
            tag: 7.2-fpm-3
            context: plugins/lando-services/services/php/7.2-fpm
          - image: php
            tag: 7.2-apache-3
            context: plugins/lando-services/services/php/7.2-apache
          # - image: php
          #   tag: 7.1-fpm-3
          #   context: plugins/lando-services/services/php/7.1-fpm
          # - image: php
          #   tag: 7.1-apache-3
          #   context: plugins/lando-services/services/php/7.1-apache
          - image: php
            tag: 7.0-fpm-3
            context: plugins/lando-services/services/php/7.0-fpm
          - image: php
            tag: 7.0-apache-3
            context: plugins/lando-services/services/php/7.0-apache
          - image: php
            tag: 5.6-fpm-3
            context: plugins/lando-services/services/php/5.6-fpm
          - image: php
            tag: 5.6-apache-3
            context: plugins/lando-services/services/php/5.6-apache

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag suffix
        id: pr
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "::set-output name=TAG_SUFFIX::-edge"
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
