name: PR Core Tests

on:
  pull_request:

jobs:
  core-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 12.x
        core-tests:
          - basics
          - badname
          - custom-landofile-name
    steps:

      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Ensure underlying lando deps are installed
      # - name: Install and config via hyperdrive
      #   run: STUFF
      # @TODO: See above ^
      - name: Verify Docker dependencies
        run: |
          docker --version | grep "20.10."
          docker-compose --version | grep "1.29."

      # We should test against a packaged version of the CLI
      # @TODO: cache the build asset?
      # @TODO: hash the version node ./scripts/dev-version.js
      - name: Build CLI
        run: yarn pkg
      - name: Replace source CLI with built one
        run: sudo mv ./dist/cli/* /usr/local/bin/lando
      - name: Verify we can run the built CLI
        run: lando version

      # - name: Disable usage and error reporting
      #   run: echo "Disable usage and error reporting"
      - name: Generate tests
        run: yarn generate:tests

      - name: Run core ${{ matrix.core-tests }} tests
        run: yarn mocha --timeout 900000 ./test/${{ matrix.core-tests }}-example.func.js
