name: PR Functional Tests

on:
  pull_request:

jobs:
  func-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 12.x
    steps:

      # Install deps and cache
      # Eventually it would be great if these steps could live in a separate YAML file
      # that could be included in line to avoid code duplication
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Here is the main thing
      - name: Take this thing into hyperspace
        run: |
          # Update needed keys
          curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
          # Spoof the public key
          ssh-keygen -t rsa -N "" -C "spoof@circle" -f "$HOME/.ssh/spoofkey"
          mv "$HOME/.ssh/spoofkey.pub" "$HOME/.ssh/id_rsa.pub"
          # Install bc
          sudo apt-get update -y
          sudo apt-get install -y bc
          # Hyperdrive
          curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.6.1/hyperdrive > /tmp/hyperdrive
          chmod +x /tmp/hyperdrive
          /tmp/hyperdrive -y --name "Lando System" --email landobot@devwithlando.io
          # @TODO: anyway hyperdrive can assert dominance here?
          sudo ln -sf /usr/bin/nodejs /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
          # We need to not enforce ssh for github because this breaks some tests
          git config --global --unset url.ssh://git@github.com.insteadof
      - name: Disable usage and error reporting
        run: echo "Disable usage and error reporting"
      - name: Switch lando over to binary built from source
        run: echo "Switch lando over to binary built from source"
      - name: Generate tests
        run: echo "Generate tests"
      - name: Run tests
        run: echo "Run tests"
